my.props.underscores.prop-with-underscores-1=aaa
my.props.underscores.prop-with-underscores-two=bbb
my.props.underscores.listPropWithUnderscoresThree[0]=aaa
my.props.underscores.list_prop_with_underscores_three[1]=bbb
my.props.named.foo=foo_value
my.props.named.bar=bar_value
my.props.named.prop2=should be not resolved!
my.props.named.pojo.buzz=pojo_buzz_value
my.props.named.pojo.prop5=pojo_not_named_value
my.props.record-named.boo=boo-value
my.props.ctor-named.dummy=dummy-value
my.props.ctor-named.prop2=prop_not_named