my.props.named.foo=foo_value
my.props.named.bar=bar_value
my.props.named.prop2=should be not resolved!
my.props.named.pojo.buzz=pojo_buzz_value
my.props.named.pojo.prop5=pojo_not_named_value
my.props.record-named.boo=boo-value
my.props.ctor-named.dummy=dummy-value
my.props.ctor-named.prop2=prop_not_named
my.props.ctor-named.pojo.buzz=pojo_buzz_value_ctor
my.props.ctor-named.pojo.prop5=pojo_not_named_value_ctor
my.props.nested-named.pojo-one.pojo-two.string=nested_pojo_value
my.props.nested-named.pojo-one.pojo-two.boolean=true
## map<string,pojo> with @Name-annotated pojo properties:
my.props.nested-named.pojo-map.key1.boolean=true
my.props.nested-named.pojo-map.key1.property=pojo-map