spring:
  application:
    name: spring-boot-configprops-names yaml
my:
  props:
    ### test the @Name annotations for properties:
    named:
      foo: foo_value yaml
      bar: bar_value yaml
      prop2: should be not resolved! yaml
      pojo:
        buzz: pojo_buzz_value yaml
        prop5: pojo_not_named_value yaml
    ### works ok with constructor binding however:
    record-named:
      boo: boo-value yaml
    ctor-named:
      dummy: dummy-value yaml
      prop2: prop_not_named yaml
      pojo:
        buzz: pojo_buzz_value_ctor yaml
        prop5: pojo_not_named_value_ctor yaml
